name: Deploy to Hetzner

on:
  push:
    branches: [ "main" ]   # runs when you push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to Hetzner (Next.js)
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
          cd /var/www/soravpn-website &&
          git pull origin main &&
          npm install &&
          NEXT_DISABLE_ESLINT=1 npm run build &&
          pm2 restart soravpn-website
        "
